---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "tripvibe.fullname" . }}
  labels:
    {{- include "tripvibe.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: DeploymentConfig
    name: {{ include "tripvibe.fullname" . }}
  minReplicas: {{ .Values.replicas.min }}
  maxReplicas: {{ .Values.replicas.max }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: 300m
