{{- if .Values.route }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "tripvibe.fullname" . }}
  labels:
    {{- include "tripvibe.labels" . | nindent 4 }}
spec:
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ include "tripvibe.fullname" . }}
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - status: 'True'
          type: Admitted
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/connects-to: infinispan
  labels:
    app: tripvibe
    app.kubernetes.io/component: sc-routes
    app.kubernetes.io/instance: sc-routes
    app.kubernetes.io/part-of: tripvibe
  name: tripvibe-sc-routes
spec:
  path: /api
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: sc-routes
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: tv-submit
    app.kubernetes.io/component: tv-submit
    app.kubernetes.io/instance: tv-submit
  name: tripvibe-tv-submit
spec:
  path: /submission
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: tv-submit
    weight: 100
  wildcardPolicy: None
{{ end }}
